# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1c6ef44608c64f8d893ad397057102b3895d649932c5306e0ed4d664031b729561fdb27ead96a8c0aae1059b892596a84d8a62e560bc13fc4cd80a665981d2

test:
  secret_key_base: 289fe29d91e6b48572d1bb12bd22dfee6c6fc1488266c34b18f858fa704ce3bbacd601102c978d5818fae99a9070ec3af00160c52cd78104f151ecab2b29f3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
